# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# environment/computational parameters
seed: 1
device: cuda
num_workers: 4

# dataset parameters
num_classes: 10

# training hyperparameters
image_size: [32, 32]
max_epochs: 16
batch_size: 128
learning_rate: 0.001
weight_decay: 0.001

# output params
output: models
